//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOAEA3.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOAEA3.Resources.ErrorResource", typeof(ErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be reset.
        /// </summary>
        public static string ACCOUNT_PASSWORD_CHANGE_REQUIRED {
            get {
                return ResourceManager.GetString("ACCOUNT_PASSWORD_CHANGE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application already exists! Cannot be created..
        /// </summary>
        public static string CANT_CREATE_APPLICATION_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("CANT_CREATE_APPLICATION_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string CANT_CREATE_OR_MODIFY_APPLICATION_UNAUTHORIZED {
            get {
                return ResourceManager.GetString("CANT_CREATE_OR_MODIFY_APPLICATION_UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t set once a value has already been set..
        /// </summary>
        public static string CANT_SET_VALUE_ONCE_SET {
            get {
                return ResourceManager.GetString("CANT_SET_VALUE_ONCE_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application does not exists! Cannot be updated..
        /// </summary>
        public static string CANT_UPDATE_APPLICATION_DOES_NOT_EXISTS {
            get {
                return ResourceManager.GetString("CANT_UPDATE_APPLICATION_DOES_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment field is too long.  Maximum length is 500 characters..
        /// </summary>
        public static string COMMENTS_TOO_LONG_500 {
            get {
                return ResourceManager.GetString("COMMENTS_TOO_LONG_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor surname cannot be XXXX.
        /// </summary>
        public static string DEBTOR_SURNAME_CANNOT_BE_XXXX {
            get {
                return ResourceManager.GetString("DEBTOR_SURNAME_CANNOT_BE_XXXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First three characters of Debtor Surname cannot contain a space.
        /// </summary>
        public static string DEBTOR_SURNAME_CANNOT_CONTAIN_SPACE {
            get {
                return ResourceManager.GetString("DEBTOR_SURNAME_CANNOT_CONTAIN_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor Surname length must be 3 or greater.
        /// </summary>
        public static string DEBTOR_SURNAME_LENGTH_3 {
            get {
                return ResourceManager.GetString("DEBTOR_SURNAME_LENGTH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments too long..
        /// </summary>
        public static string ERROR_COMMENTS_TOO_LONG {
            get {
                return ResourceManager.GetString("ERROR_COMMENTS_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must match someone@somewhere.abc.
        /// </summary>
        public static string ERROR_EMAIL_FORMAT {
            get {
                return ResourceManager.GetString("ERROR_EMAIL_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string ERROR_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("ERROR_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        public static string ERROR_INVALID_PHONE {
            get {
                return ResourceManager.GetString("ERROR_INVALID_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a language preference.
        /// </summary>
        public static string ERROR_LANGUAGE_MISSING {
            get {
                return ResourceManager.GetString("ERROR_LANGUAGE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an area number.
        /// </summary>
        public static string ERROR_MISSING_PHONE_AREACODE {
            get {
                return ResourceManager.GetString("ERROR_MISSING_PHONE_AREACODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a telephone number.
        /// </summary>
        public static string ERROR_MISSING_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("ERROR_MISSING_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No role was selected..
        /// </summary>
        public static string ERROR_MISSING_ROLE {
            get {
                return ResourceManager.GetString("ERROR_MISSING_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing status.
        /// </summary>
        public static string ERROR_MISSING_STATUS {
            get {
                return ResourceManager.GetString("ERROR_MISSING_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Submitter First Name.
        /// </summary>
        public static string ERROR_MISSING_SUBM_FIRSTNAME {
            get {
                return ResourceManager.GetString("ERROR_MISSING_SUBM_FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Submitter Surname.
        /// </summary>
        public static string ERROR_MISSING_SUBM_SURNAME {
            get {
                return ResourceManager.GetString("ERROR_MISSING_SUBM_SURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical data only.
        /// </summary>
        public static string ERROR_NOT_A_NUMBER {
            get {
                return ResourceManager.GetString("ERROR_NOT_A_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation code is not valid.
        /// </summary>
        public static string INVALID_CONFIRMATION {
            get {
                return ResourceManager.GetString("INVALID_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Control Code.
        /// </summary>
        public static string INVALID_CONTROL_CODE {
            get {
                return ResourceManager.GetString("INVALID_CONTROL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Debtor Surname.
        /// </summary>
        public static string INVALID_DEBTOR_SURNAME {
            get {
                return ResourceManager.GetString("INVALID_DEBTOR_SURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Frequency Payment Code (&lt;dat_PymPr_Cd&gt;).
        /// </summary>
        public static string INVALID_FREQUENCY_PAYMENT_CODE {
            get {
                return ResourceManager.GetString("INVALID_FREQUENCY_PAYMENT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username provided.
        /// </summary>
        public static string INVALID_LOGIN {
            get {
                return ResourceManager.GetString("INVALID_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email associated with UserName.
        /// </summary>
        public static string INVALID_LOGIN_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_LOGIN_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password provided.
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid purpose. Must be 1, 2 or 3..
        /// </summary>
        public static string INVALID_PURPOSE {
            get {
                return ResourceManager.GetString("INVALID_PURPOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot request financial information for purpose 1..
        /// </summary>
        public static string INVALID_REQUEST_FINANCIAL_DATA {
            get {
                return ResourceManager.GetString("INVALID_REQUEST_FINANCIAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot request SIN information for purpose 1..
        /// </summary>
        public static string INVALID_REQUEST_SIN_DATA {
            get {
                return ResourceManager.GetString("INVALID_REQUEST_SIN_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tracing information requested. Cannot request employer address for purpose 3..
        /// </summary>
        public static string INVALID_TRACING_INFORMATION_TYPE {
            get {
                return ResourceManager.GetString("INVALID_TRACING_INFORMATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string INVALID_USERNAME_OR_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_USERNAME_OR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Variations issue Date.
        /// </summary>
        public static string INVALID_VARIATIONS_ISSUE_DATE {
            get {
                return ResourceManager.GetString("INVALID_VARIATIONS_ISSUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of the control code is 6.
        /// </summary>
        public static string MAX_CONTROL_CODE_LENGTH {
            get {
                return ResourceManager.GetString("MAX_CONTROL_CODE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The particulars of the specified family provision breach must be specified.
        /// </summary>
        public static string MISSING_BREACH {
            get {
                return ResourceManager.GetString("MISSING_BREACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category code must be specified.
        /// </summary>
        public static string MISSING_CATEGORY_CODE {
            get {
                return ResourceManager.GetString("MISSING_CATEGORY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control code must be specified.
        /// </summary>
        public static string MISSING_CONTROL_CODE {
            get {
                return ResourceManager.GetString("MISSING_CONTROL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creditor first name must be specified.
        /// </summary>
        public static string MISSING_CREDITOR_FIRST_NAME {
            get {
                return ResourceManager.GetString("MISSING_CREDITOR_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creditor surname must be specified.
        /// </summary>
        public static string MISSING_CREDITOR_SURNAME {
            get {
                return ResourceManager.GetString("MISSING_CREDITOR_SURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debtor date of birth must be specified.
        /// </summary>
        public static string MISSING_DEBTOR_DOB {
            get {
                return ResourceManager.GetString("MISSING_DEBTOR_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debtor first name must be specified.
        /// </summary>
        public static string MISSING_DEBTOR_FIRST_NAME {
            get {
                return ResourceManager.GetString("MISSING_DEBTOR_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debtor surname must be specified.
        /// </summary>
        public static string MISSING_DEBTOR_SURNAME {
            get {
                return ResourceManager.GetString("MISSING_DEBTOR_SURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enforcement service code must be specified.
        /// </summary>
        public static string MISSING_ENFSRV_CODE {
            get {
                return ResourceManager.GetString("MISSING_ENFSRV_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The family provision breach must be specified.
        /// </summary>
        public static string MISSING_FAMPRO {
            get {
                return ResourceManager.GetString("MISSING_FAMPRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gender must be specified.
        /// </summary>
        public static string MISSING_GENDER {
            get {
                return ResourceManager.GetString("MISSING_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group batch code must be specified.
        /// </summary>
        public static string MISSING_GROUP_BATCH_CODE {
            get {
                return ResourceManager.GetString("MISSING_GROUP_BATCH_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The medium code must be specified.
        /// </summary>
        public static string MISSING_MEDIUM_CODE {
            get {
                return ResourceManager.GetString("MISSING_MEDIUM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purpose must be specified.
        /// </summary>
        public static string MISSING_PURPOSE {
            get {
                return ResourceManager.GetString("MISSING_PURPOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipient submitter must be specified.
        /// </summary>
        public static string MISSING_RECIPIENT_SUBMITTER {
            get {
                return ResourceManager.GetString("MISSING_RECIPIENT_SUBMITTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The submitter must be specified.
        /// </summary>
        public static string MISSING_SUBMITTER {
            get {
                return ResourceManager.GetString("MISSING_SUBMITTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic Amount (&lt;dat_IntFinH_Perpym_Money&gt;) provided with no frequency payment code (&lt;dat_PymPr_Cd&gt;).
        /// </summary>
        public static string PERIODIC_AMOUNT_MISSING_FREQUENCY_CODE {
            get {
                return ResourceManager.GetString("PERIODIC_AMOUNT_MISSING_FREQUENCY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic Payment Amount (&lt;dat_IntFinH_Perpym_Money&gt;) was submitted with an amount &gt; 0. Cumulative Payment Indicator (&lt;dat_IntFinH_CmlPrPym_Ind&gt;) does not exist or is invalid.
        /// </summary>
        public static string PERIODIC_PAYMENT_AMOUNT_IS_0_MISSING_CUMULATIVE_PAYMENT_INDICATOR {
            get {
                return ResourceManager.GetString("PERIODIC_PAYMENT_AMOUNT_IS_0_MISSING_CUMULATIVE_PAYMENT_INDICATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value specified for the reference code must be alphanumeric.
        /// </summary>
        public static string REQUIRED_ALPHANUMERIC_CONTROL_CODE {
            get {
                return ResourceManager.GetString("REQUIRED_ALPHANUMERIC_CONTROL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success. Periodic Payment Amount (&lt;dat_IntFinH_Perpym_Money&gt;) was not submitted. All data for Periodic Payment Amount (&lt;dat_IntFinH_Perpym_Money&gt;), Frequency Payment Code (&lt;PymPr_Cd&gt;) and Cumulative Payment Indicator (&lt;dat_IntFinH_CmlPrPym_Ind&gt;) has been removed.
        /// </summary>
        public static string SUCCESS_PERIODIC_PAYMENT_AMOUNT_MISSING {
            get {
                return ResourceManager.GetString("SUCCESS_PERIODIC_PAYMENT_AMOUNT_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No duties were selected.
        /// </summary>
        public static string WARNING_NO_DUTIES {
            get {
                return ResourceManager.GetString("WARNING_NO_DUTIES", resourceCulture);
            }
        }
    }
}
