//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOAEA3.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FOAEA3.Resources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New From Current.
        /// </summary>
        public static string ADD_NEW_FROM_CURRENT {
            get {
                return ResourceManager.GetString("ADD_NEW_FROM_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ALL_LABEL {
            get {
                return ResourceManager.GetString("ALL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of arrears.
        /// </summary>
        public static string AMOUNT_OF_ARREARS {
            get {
                return ResourceManager.GetString("AMOUNT_OF_ARREARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string APPL_COMMENT {
            get {
                return ResourceManager.GetString("APPL_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Manager.
        /// </summary>
        public static string APPLICATION_MANAGER {
            get {
                return ResourceManager.GetString("APPLICATION_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Reference Number.
        /// </summary>
        public static string APPLICATION_REFERENCE_NUMBER {
            get {
                return ResourceManager.GetString("APPLICATION_REFERENCE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assume Role.
        /// </summary>
        public static string ASSUME_ROLE {
            get {
                return ResourceManager.GetString("ASSUME_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforcement Service Code\tControl Code\tSource Reference Number\tApplication Message.
        /// </summary>
        public static string AUDIT_HEADER_TITLES {
            get {
                return ResourceManager.GetString("AUDIT_HEADER_TITLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string AUDIT_SECTION {
            get {
                return ResourceManager.GetString("AUDIT_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string AUDIT_SUCCESS {
            get {
                return ResourceManager.GetString("AUDIT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string CHANGE_PASSWORD_CONFIRM_LABEL {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_CONFIRM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new permanent password must confirm with the following standard: - Minimum of 8 alphanumerical characters; - Choose one or more of at least three of: one digit, one lower case letter, one uppercase letter and one special character; - Cannot contain the portion of your user account name that is found before or after the dash (-); - Should not be a password already used in the past.
        /// </summary>
        public static string CHANGE_PASSWORD_FAILS_REQUIREMENTS {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_FAILS_REQUIREMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string CHANGE_PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        public static string CHANGE_PASSWORD_MATCH_ERROR {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_MATCH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string CHANGE_PASSWORD_NEW_LABEL {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_NEW_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        public static string CHANGE_PASSWORD_SUCCESSFUL {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string COMMENTS {
            get {
                return ResourceManager.GetString("COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Code.
        /// </summary>
        public static string CONFIRMATION_CODE_LABEL {
            get {
                return ResourceManager.GetString("CONFIRMATION_CODE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains invalid tag.
        /// </summary>
        public static string CONTAINS_INVALID_TAG {
            get {
                return ResourceManager.GetString("CONTAINS_INVALID_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Code.
        /// </summary>
        public static string CONTROL_CODE {
            get {
                return ResourceManager.GetString("CONTROL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of court.
        /// </summary>
        public static string COURT_NAME {
            get {
                return ResourceManager.GetString("COURT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court User.
        /// </summary>
        public static string COURT_USER {
            get {
                return ResourceManager.GetString("COURT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data was updated successfully..
        /// </summary>
        public static string DATA_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("DATA_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City of birth.
        /// </summary>
        public static string DEBTOR_BIRTH_CITY {
            get {
                return ResourceManager.GetString("DEBTOR_BIRTH_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of birth.
        /// </summary>
        public static string DEBTOR_BIRTH_COUNTRY {
            get {
                return ResourceManager.GetString("DEBTOR_BIRTH_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string DEBTOR_HEIGHT {
            get {
                return ResourceManager.GetString("DEBTOR_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest known address.
        /// </summary>
        public static string DEBTOR_LAST_ADDRESS {
            get {
                return ResourceManager.GetString("DEBTOR_LAST_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string DEBTOR_LAST_CITY {
            get {
                return ResourceManager.GetString("DEBTOR_LAST_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string DEBTOR_LAST_COUNTRYCODE {
            get {
                return ResourceManager.GetString("DEBTOR_LAST_COUNTRYCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string DEBTOR_LAST_POSTALCODE {
            get {
                return ResourceManager.GetString("DEBTOR_LAST_POSTALCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province/Territory/State.
        /// </summary>
        public static string DEBTOR_LAST_PROVCODE {
            get {
                return ResourceManager.GetString("DEBTOR_LAST_PROVCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOJ Financial Officer.
        /// </summary>
        public static string DOJ_FINANCIAL_OFFICER {
            get {
                return ResourceManager.GetString("DOJ_FINANCIAL_OFFICER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duties.
        /// </summary>
        public static string DUTIES {
            get {
                return ResourceManager.GetString("DUTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string EMPLOYER_ADDRESS_CITY {
            get {
                return ResourceManager.GetString("EMPLOYER_ADDRESS_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string EMPLOYER_ADDRESS_COUNTRYCODE {
            get {
                return ResourceManager.GetString("EMPLOYER_ADDRESS_COUNTRYCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string EMPLOYER_ADDRESS_POSTALCODE {
            get {
                return ResourceManager.GetString("EMPLOYER_ADDRESS_POSTALCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province/Territory/State.
        /// </summary>
        public static string EMPLOYER_ADDRESS_PROVCODE {
            get {
                return ResourceManager.GetString("EMPLOYER_ADDRESS_PROVCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer address.
        /// </summary>
        public static string EMPLOYER_ADDRESS1 {
            get {
                return ResourceManager.GetString("EMPLOYER_ADDRESS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer name.
        /// </summary>
        public static string EMPLOYER_NAME {
            get {
                return ResourceManager.GetString("EMPLOYER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforcement Office.
        /// </summary>
        public static string ENFORCEMENT_OFFICE {
            get {
                return ResourceManager.GetString("ENFORCEMENT_OFFICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforcement Service.
        /// </summary>
        public static string ENFORCEMENT_SERVICE {
            get {
                return ResourceManager.GetString("ENFORCEMENT_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ERROR_LABEL {
            get {
                return ResourceManager.GetString("ERROR_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors detected.
        /// </summary>
        public static string ERRORS_DETECTED {
            get {
                return ResourceManager.GetString("ERRORS_DETECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour of eyes.
        /// </summary>
        public static string EYE_COLOUR {
            get {
                return ResourceManager.GetString("EYE_COLOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string FAX {
            get {
                return ResourceManager.GetString("FAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string FINANCE {
            get {
                return ResourceManager.GetString("FINANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FIRST_NAME {
            get {
                return ResourceManager.GetString("FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string GENDER {
            get {
                return ResourceManager.GetString("GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if known.
        /// </summary>
        public static string IF_KNOWN {
            get {
                return ResourceManager.GetString("IF_KNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string INFO_LABEL {
            get {
                return ResourceManager.GetString("INFO_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interception.
        /// </summary>
        public static string INTERCEPTION {
            get {
                return ResourceManager.GetString("INTERCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language of choice.
        /// </summary>
        public static string LANGUAGE_OF_CHOICE {
            get {
                return ResourceManager.GetString("LANGUAGE_OF_CHOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Preference.
        /// </summary>
        public static string LANGUAGE_PREFERENCE {
            get {
                return ResourceManager.GetString("LANGUAGE_PREFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login.
        /// </summary>
        public static string LAST_LOGIN {
            get {
                return ResourceManager.GetString("LAST_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License - Denial.
        /// </summary>
        public static string LICENSE_DENIAL {
            get {
                return ResourceManager.GetString("LICENSE_DENIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded records.
        /// </summary>
        public static string LOADED_RECORDS {
            get {
                return ResourceManager.GetString("LOADED_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LOGOUT {
            get {
                return ResourceManager.GetString("LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string MENU_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("MENU_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s surname at her birth.
        /// </summary>
        public static string MOTHER_MAIDEN_NAME {
            get {
                return ResourceManager.GetString("MOTHER_MAIDEN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date notice sent to debtor.
        /// </summary>
        public static string NOTICESENTTODEBTOR_DTE {
            get {
                return ResourceManager.GetString("NOTICESENTTODEBTOR_DTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of records.
        /// </summary>
        public static string NUMBER_OF_RECORDS {
            get {
                return ResourceManager.GetString("NUMBER_OF_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of payments in default.
        /// </summary>
        public static string NUMBER_PAYMENTS_IN_DEFAULT {
            get {
                return ResourceManager.GetString("NUMBER_PAYMENTS_IN_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK_LABEL {
            get {
                return ResourceManager.GetString("OK_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has already been used.
        /// </summary>
        public static string PASSWORD_USED {
            get {
                return ResourceManager.GetString("PASSWORD_USED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment period code.
        /// </summary>
        public static string PAYMENT_PERIOD_CODE {
            get {
                return ResourceManager.GetString("PAYMENT_PERIOD_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string PROVINCE {
            get {
                return ResourceManager.GetString("PROVINCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        public static string READ_ONLY {
            get {
                return ResourceManager.GetString("READ_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records not loaded.
        /// </summary>
        public static string RECORDS_NOT_LOADED {
            get {
                return ResourceManager.GetString("RECORDS_NOT_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records removed from file.
        /// </summary>
        public static string RECORDS_REMOVED_FROM_FILE {
            get {
                return ResourceManager.GetString("RECORDS_REMOVED_FROM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset email sent to user.
        /// </summary>
        public static string RESET_EMAIL_SENT {
            get {
                return ResourceManager.GetString("RESET_EMAIL_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password/Unlock account.
        /// </summary>
        public static string RESET_PASSWORD {
            get {
                return ResourceManager.GetString("RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string ROLE {
            get {
                return ResourceManager.GetString("ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name.
        /// </summary>
        public static string SECOND_NAME {
            get {
                return ResourceManager.GetString("SECOND_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Submitter.
        /// </summary>
        public static string SELECT_SUBMITTER {
            get {
                return ResourceManager.GetString("SELECT_SUBMITTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Password.
        /// </summary>
        public static string SEND_PASSWORD {
            get {
                return ResourceManager.GetString("SEND_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Insurance Number.
        /// </summary>
        public static string SIN {
            get {
                return ResourceManager.GetString("SIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string SIN_CONFIRMED {
            get {
                return ResourceManager.GetString("SIN_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string SIN_NOTCONFIRMED {
            get {
                return ResourceManager.GetString("SIN_NOTCONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data submitted, .
        /// </summary>
        public static string SINDATASENT {
            get {
                return ResourceManager.GetString("SINDATASENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SUBMIT_ENTER {
            get {
                return ResourceManager.GetString("SUBMIT_ENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Database.
        /// </summary>
        public static string SUBMIT_LOGIN {
            get {
                return ResourceManager.GetString("SUBMIT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitter.
        /// </summary>
        public static string SUBMITTER {
            get {
                return ResourceManager.GetString("SUBMITTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitter Code.
        /// </summary>
        public static string SUBMITTER_CODE {
            get {
                return ResourceManager.GetString("SUBMITTER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitter Title.
        /// </summary>
        public static string SUBMITTER_TITLE {
            get {
                return ResourceManager.GetString("SUBMITTER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of support order or provision.
        /// </summary>
        public static string SUPPORTORDER_DTE {
            get {
                return ResourceManager.GetString("SUPPORTORDER_DTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string SURNAME {
            get {
                return ResourceManager.GetString("SURNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swears Affidavits.
        /// </summary>
        public static string SWEARS_AFFIDAVITS {
            get {
                return ResourceManager.GetString("SWEARS_AFFIDAVITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Manager.
        /// </summary>
        public static string SYSTEM_MANAGER {
            get {
                return ResourceManager.GetString("SYSTEM_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string TELEPHONE {
            get {
                return ResourceManager.GetString("TELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination date.
        /// </summary>
        public static string TERM_REQ_DATE {
            get {
                return ResourceManager.GetString("TERM_REQ_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total XML validation warnings.
        /// </summary>
        public static string TOTAL_XML_VALIDATION_WARNINGS {
            get {
                return ResourceManager.GetString("TOTAL_XML_VALIDATION_WARNINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracing.
        /// </summary>
        public static string TRACING {
            get {
                return ResourceManager.GetString("TRACING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used By.
        /// </summary>
        public static string USER_BY {
            get {
                return ResourceManager.GetString("USER_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string USER_NAME_LABEL {
            get {
                return ResourceManager.GetString("USER_NAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIN  Not Confirmed.
        /// </summary>
        public static string VALSTAT__NOTCONFIRMED {
            get {
                return ResourceManager.GetString("VALSTAT__NOTCONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIN Confirmed.
        /// </summary>
        public static string VALSTAT_CONFIRMED {
            get {
                return ResourceManager.GetString("VALSTAT_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WARNING_LABEL {
            get {
                return ResourceManager.GetString("WARNING_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the FOAEA national enforcement services..
        /// </summary>
        public static string WELCOME_GREETING {
            get {
                return ResourceManager.GetString("WELCOME_GREETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML validation warnings.
        /// </summary>
        public static string XML_VALIDATION_WARNINGS {
            get {
                return ResourceManager.GetString("XML_VALIDATION_WARNINGS", resourceCulture);
            }
        }
    }
}
