start /D "C:\dev-repos\foaea-laeoef-r\FileBroker.API.Fed.LicenceDenial\bin\Debug\net6.0\" FileBroker.API.Fed.LicenceDenial.exe
start /D "C:\dev-repos\foaea-laeoef-r\FileBroker.API.Fed.Interception\bin\Debug\net6.0\" FileBroker.API.Fed.Interception.exe
start /D "C:\dev-repos\foaea-laeoef-r\FileBroker.API.Fed.Tracing\bin\Debug\net6.0\" FileBroker.API.Fed.Tracing.exe
start /D "C:\dev-repos\foaea-laeoef-r\FileBroker.API.Fed.SIN\bin\Debug\net6.0\" FileBroker.API.Fed.SIN.exe
start /D "C:\dev-repos\foaea-laeoef-r\FileBroker.API.MEP.Interception\bin\Debug\net6.0" FileBroker.API.MEP.Interception.exe
start /D "C:\dev-repos\foaea-laeoef-r\FileBroker.API.MEP.LicenceDenial\bin\Debug\net6.0" FileBroker.API.MEP.LicenceDenial.exe
start /D "C:\dev-repos\foaea-laeoef-r\FileBroker.API.MEP.Tracing\bin\Debug\net6.0" FileBroker.API.MEP.Tracing.exe
start /D "C:\dev-repos\foaea-laeoef-r\BackendProcesses.API\bin\Debug\net6.0" BackendProcesses.API.exe
start /D "C:\dev-repos\foaea-laeoef-r\FOAEA3.API\bin\Debug\net6.0" FOAEA3.API.exe
start /D "C:\dev-repos\foaea-laeoef-r\FOAEA3.API.Interception\bin\Debug\net6.0" FOAEA3.API.Interception.exe
start /D "C:\dev-repos\foaea-laeoef-r\FOAEA3.API.LicenceDenial\bin\Debug\net6.0" FOAEA3.API.LicenceDenial.exe
start /D "C:\dev-repos\foaea-laeoef-r\FOAEA3.API.Tracing\bin\Debug\net6.0" FOAEA3.API.Tracing.exe